version: "3.9"

services:
  3cx:
    image: izerxyz/3cx:latest
    container_name: 3cx
    restart: unless-stopped
    ports:
      - "5001:5001/tcp"
      - "5015:5015/tcp"
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/tcp"
      - "5090:5090/tcp"
      - "5090:5090/udp"
      - "9000-10999:9000-10999/udp"
    networks:
      - voip
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - 3cx_var:/var/lib/3cxpbx
      - 3cx_etc:/etc/3cxpbx
      - 3cx_mnt:/mnt/3cx

networks:
  voip:

volumes:
  3cx_var:
  3cx_etc:
  3cx_mnt:
