version: "3.9"

services:
  3cx:
    image: izerxyz/3cx:latest   # or pin a tag from Docker Hub
    container_name: 3cx
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Vancouver
      # Optional for auto-restore if your image supports it:
      # - CX_BACKUP_FILE=/mnt/3cx/backup.zip
    # Many 3CX images boot systemd; these mounts help if required:
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - 3cx_var:/var/lib/3cxpbx
      - 3cx_etc:/etc/3cxpbx
      - 3cx_mnt:/mnt/3cx

volumes:
  3cx_var:
  3cx_etc:
  3cx_mnt:
