version: "3.9"

services:
  3cx:
    image: ghcr.io/jamesits/3cx:15.5  # Prebuilt 3CX v15.5 image
    container_name: 3cx
    privileged: true
    restart: unless-stopped
    ports:
      - "5000-5099:5000-5099"         # HTTP ports for management and SIP
      - "9000-10999:9000-10999/udp"   # SIP and RTP UDP ports
    dns:
      - "1.1.1.1"  # Set DNS (use Cloudflare DNS here)
    volumes:
      - 3cx-data:/var/lib/3cxpbx  # Persist data

volumes:
  3cx-data:
